name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 소스 코드 체크아웃
        uses: actions/checkout@v3

      - name: EC2에 SSH로 연결하여 배포
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/mongle-back
            git pull origin main
            sudo docker stop mongle || true
            sudo docker rm mongle || true
            sudo docker rmi mongle || true
            sudo docker build -t mongle .
            sudo docker run -d -p 8080:8080 --name mongle mongle
