name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 소스 코드 체크아웃
        uses: actions/checkout@v3

      - name: EC2에 SSH로 연결하여 배포
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/mongle-back
            git pull origin main
            docker stop mongle || true
            docker rm mongle || true
            docker rmi mongle || true
            docker build -t mongle .
            docker run -d -p 8080:8080 --name mongle mongle
